
export default {

	PUSH_RECEIVED: 'PUSH_RECEIVED',
	SEAT_AVAILABILITY: 'SEAT_AVAILABILITY',
	SEAT_RESERVED: 'SEAT_RESERVED',
	SET_USER: 'SET_USER',
	ALLREADY_REGISTRED: 'ALLREADY_REGISTRED',
	REMOVED_FROM_QUEUE: 'REMOVED_FROM_QUEUE'
}

